services:
  api:
    build:
      context: .
      dockerfile: ExpenseTracker.API/Dockerfile
    container_name: expense-tracker-api
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development        
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=db;Username=admin;Password=admin;      
      - Serilog__WriteTo__0__Name=Console
  frontend:
    build:
      context: ../expense-tracker-frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:5000
    container_name: expense-tracker-frontend
    ports:
      - "5001:80"   
  postgres:
    image: postgres:16-alpine
    container_name: expense-tracker-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: expense-tracker-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: